# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\大学\huawei\hisensor\chooseitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chooseitem(object):
    def setupUi(self, Chooseitem):
        Chooseitem.setObjectName("Chooseitem")
        Chooseitem.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Chooseitem.sizePolicy().hasHeightForWidth())
        Chooseitem.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\大学\\huawei\\hisensor\\nakelulu.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Chooseitem.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Chooseitem)
        self.verticalLayout.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(60, -1, 60, -1)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Chooseitem)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Chooseitem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Chooseitem)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Chooseitem)
        self.buttonBox.accepted.connect(Chooseitem.accept)
        self.buttonBox.rejected.connect(Chooseitem.reject)
        QtCore.QMetaObject.connectSlotsByName(Chooseitem)

    def retranslateUi(self, Chooseitem):
        _translate = QtCore.QCoreApplication.translate
        Chooseitem.setWindowTitle(_translate("Chooseitem", "选择选项"))
        self.label.setText(_translate("Chooseitem", "选项名："))
